set(CMAKE_C_COMPILER ${CURRENT_MUSL_CC_TARGET}-gcc)
set(CMAKE_CXX_COMPILER ${CURRENT_MUSL_CC_TARGET}-g++)

if (CMAKE_BUILD_TYPE MATCHES "Debug")
    set(CMAKE_STAGING_PREFIX ${PROJECT_SOURCE_DIR}/targets/${CURRENT_MUSL_CC_TARGET}/Debug)
elseif (CMAKE_BUILD_TYPE MATCHES "Release")
    set(CMAKE_STAGING_PREFIX ${PROJECT_SOURCE_DIR}/targets/${CURRENT_MUSL_CC_TARGET}/Release)
elseif (CMAKE_BUILD_TYPE MATCHES "RelWitchDebInfo")
    set(CMAKE_STAGING_PREFIX ${PROJECT_SOURCE_DIR}/targets/${CURRENT_MUSL_CC_TARGET}/RelWitchDebInfo)
elseif (CMAKE_BUILD_TYPE MATCHES "MinSizeRel")
    set(CMAKE_STAGING_PREFIX ${PROJECT_SOURCE_DIR}/targets/${CURRENT_MUSL_CC_TARGET}/MinSizeRel)
else ()
    set(CMAKE_STAGING_PREFIX ${PROJECT_SOURCE_DIR}/targets/${CURRENT_MUSL_CC_TARGET})
endif()



set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)