wget -P ./  https://musl.cc/aarch64-linux-musl-cross.tgz
wget -P ./  https://musl.cc/aarch64_be-linux-musl-cross.tgz
wget -P ./  https://musl.cc/arm-linux-musleabi-cross.tgz
wget -P ./  https://musl.cc/arm-linux-musleabihf-cross.tgz
wget -P ./  https://musl.cc/armeb-linux-musleabi-cross.tgz
wget -P ./  https://musl.cc/armeb-linux-musleabihf-cross.tgz
wget -P ./  https://musl.cc/armel-linux-musleabi-cross.tgz
wget -P ./  https://musl.cc/armel-linux-musleabihf-cross.tgz
wget -P ./  https://musl.cc/armv5l-linux-musleabihf-cross.tgz
wget -P ./  https://musl.cc/armv7l-linux-musleabihf-cross.tgz
wget -P ./  https://musl.cc/armv7m-linux-musleabi-cross.tgz
wget -P ./  https://musl.cc/armv7r-linux-musleabihf-cross.tgz
wget -P ./  https://musl.cc/i486-linux-musl-cross.tgz
wget -P ./  https://musl.cc/i686-linux-musl-cross.tgz
wget -P ./  https://musl.cc/i686-w64-mingw32-cross.tgz
wget -P ./  https://musl.cc/m68k-linux-musl-cross.tgz
wget -P ./  https://musl.cc/microblaze-linux-musl-cross.tgz
wget -P ./  https://musl.cc/microblazeel-linux-musl-cross.tgz
wget -P ./  https://musl.cc/mips-linux-musl-cross.tgz
wget -P ./  https://musl.cc/mips-linux-musln32sf-cross.tgz
wget -P ./  https://musl.cc/mips-linux-muslsf-cross.tgz
wget -P ./  https://musl.cc/mips64-linux-musl-cross.tgz
wget -P ./  https://musl.cc/mips64-linux-musln32-cross.tgz
wget -P ./  https://musl.cc/mips64-linux-musln32sf-cross.tgz
wget -P ./  https://musl.cc/mips64el-linux-musl-cross.tgz
wget -P ./  https://musl.cc/mips64el-linux-musln32-cross.tgz
wget -P ./  https://musl.cc/mips64el-linux-musln32sf-cross.tgz
wget -P ./  https://musl.cc/mipsel-linux-musl-cross.tgz
wget -P ./  https://musl.cc/mipsel-linux-musln32-cross.tgz
wget -P ./  https://musl.cc/mipsel-linux-musln32sf-cross.tgz
wget -P ./  https://musl.cc/mipsel-linux-muslsf-cross.tgz
wget -P ./  https://musl.cc/or1k-linux-musl-cross.tgz
wget -P ./  https://musl.cc/powerpc-linux-musl-cross.tgz
wget -P ./  https://musl.cc/powerpc-linux-muslsf-cross.tgz
wget -P ./  https://musl.cc/powerpc64-linux-musl-cross.tgz
wget -P ./  https://musl.cc/powerpc64le-linux-musl-cross.tgz
wget -P ./  https://musl.cc/powerpcle-linux-musl-cross.tgz
wget -P ./  https://musl.cc/powerpcle-linux-muslsf-cross.tgz
wget -P ./  https://musl.cc/riscv64-linux-musl-cross.tgz
wget -P ./  https://musl.cc/s390x-linux-musl-cross.tgz
wget -P ./  https://musl.cc/sh2-linux-musl-cross.tgz
wget -P ./  https://musl.cc/sh2-linux-muslfdpic-cross.tgz
wget -P ./  https://musl.cc/sh2eb-linux-musl-cross.tgz
wget -P ./  https://musl.cc/sh2eb-linux-muslfdpic-cross.tgz
wget -P ./  https://musl.cc/sh4-linux-musl-cross.tgz
wget -P ./  https://musl.cc/sh4eb-linux-musl-cross.tgz
wget -P ./  https://musl.cc/x86_64-linux-musl-cross.tgz
wget -P ./  https://musl.cc/x86_64-linux-muslx32-cross.tgz
wget -P ./  https://musl.cc/x86_64-w64-mingw32-cross.tgz

#tar zxvf ./*.tgz
ls *.tgz | xargs -n1 tar zxvf